version: '3'
services:
  otel-agent:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "55680:55680"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    depends_on:
      - otel-agent
      
  app:
    build: .
    environment:
      - WEATHER_API=http://172.23.128.46:8081/
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SERVICE_NAME=weather-input-service
    ports:
      - "8080:8080"
    depends_on:
      - otel-agent
      - zipkin
  