### SERVIÇO A
### SUCCESS
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": "80010000"
}

###
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": "01153000"
}

###
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": "29600000"
}

### ZIPCODE MUST BE STRING
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": 123465
}

### INVALID ZIPCODE
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": "011530000"
}

### INVALID ZIPCODE
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": "52544"
}

### INVALID ZIPCODE
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": ""
}

### ZIP CODE NOT FOUND
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": "00000000"
}

### INVALID ZIPCODE
POST http://localhost:8080/weather
Content-Type: application/json

{
    "cep": "abc"
}

### SERVIÇO B
### SUCCESS
GET http://localhost:8081/80010000 HTTP/1.1

### INVALID ZIPCODE
GET http://localhost:8081/123465 HTTP/1.1

### INVALID ZIPCODE
GET http://localhost:8081/011530000 HTTP/1.1

### ZIP CODE NOT FOUND
GET http://localhost:8081/00000000 HTTP/1.1

### ZIPCODE NOT FOUND
GET http://localhost:8081/52544517 HTTP/1.1

